### ISSUE TITLE
Run convert.exe error File "convert.py", line 76, in <module>

### ISSUE THREAD

**Issue by Arlinlol** [RomanGryzodub/xpt_to_xlsx_converter#1]
Traceback (most recent call last):
  File "convert.py", line 76, in <module>
  File "tkinter\__init__.py", line 2155, in wm_iconbitmap
_tkinter.TclError: bitmap "icon.ico" not defined

**Comment by RomanGryzodub** [comment]
The icon.ico file must be located in the same root directory.
